/**
 * Production Specification PDF Document
 *
 * Main PDF document component that composes all production spec sections.
 * This generates a complete production specification document for factory/workshop use.
 */

import { Document, Page, View, Text } from '@react-pdf/renderer';
import { styles } from './styles';
import type { ProductionSpecData } from './types';

// Section components
import { HeaderSection } from './sections/HeaderSection';
import { CabinetSchedule } from './sections/CabinetSchedule';
import { PanelSchedule } from './sections/PanelSchedule';
import { EdgeBandingSchedule } from './sections/EdgeBandingSchedule';
import { HardwareList } from './sections/HardwareList';
import { DrillingSchedule } from './sections/DrillingSchedule';
import { AssemblyGroups } from './sections/AssemblyGroups';

interface ProductionSpecPDFProps {
  data: ProductionSpecData;
}

/**
 * Main PDF document component
 *
 * Renders a complete production specification with:
 * - Header with order info
 * - Cabinet schedule table
 * - Panel schedule (cutting list) table
 * - Edge banding schedule
 * - Hardware BOM
 * - Drilling schedule with hole positions
 * - Assembly groups showing panel-to-cabinet relationships
 */
export function ProductionSpecPDF({ data }: ProductionSpecPDFProps) {
  return (
    <Document
      title={`Production Spec - ${data.order.orderNumber}`}
      author="North South Carpentry"
      subject={`Production specification for order ${data.order.orderNumber}`}
      creator="North South Platform"
    >
      <Page size="A4" style={styles.page}>
        {/* Header Section */}
        <HeaderSection order={data.order} />

        {/* Cabinet Schedule */}
        {data.cabinets.length > 0 && (
          <CabinetSchedule cabinets={data.cabinets} />
        )}

        {/* Panel Schedule (Cutting List) */}
        {data.panels.length > 0 && <PanelSchedule panels={data.panels} />}

        {/* Edge Banding Schedule */}
        {data.edgeBanding.length > 0 && (
          <EdgeBandingSchedule edgeBanding={data.edgeBanding} />
        )}

        {/* Hardware List (BOM) */}
        {data.hardware.length > 0 && <HardwareList hardware={data.hardware} />}

        {/* Page break for drilling and assembly sections */}
      </Page>

      {/* Drilling Schedule - New page for better readability */}
      {data.drilling.length > 0 && (
        <Page size="A4" style={styles.page}>
          <DrillingSchedule drilling={data.drilling} />
        </Page>
      )}

      {/* Assembly Groups - New page for better readability */}
      {data.assembly.length > 0 && (
        <Page size="A4" style={styles.page}>
          <AssemblyGroups assembly={data.assembly} />
        </Page>
      )}

      {/* Footer on last page */}
      <Page size="A4" style={styles.page}>
        <View style={[styles.section, { marginTop: 'auto' }]}>
          <View style={styles.sectionDivider} />
          <Text style={[styles.textSmall, styles.textMuted, { textAlign: 'center' }]}>
            Generated by North South Platform • Order: {data.order.orderNumber}
          </Text>
          <Text style={[styles.textSmall, styles.textMuted, { textAlign: 'center' }]}>
            For questions, contact North South Carpentry
          </Text>
        </View>
      </Page>
    </Document>
  );
}
